### ISSUE TITLE
@prisma/client did not initialize yet

### ISSUE THREAD

**Issue by bboysoulcn** [umami-software/migrate-v1-v2#1]
```bash
root@01edbeefcd1f:/# npx @umami/migrate-v1-v2
Database type detected: mysql
✓ Copied /root/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/db/mysql to /root/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/prisma
prisma:warn The postinstall script automatically ran `prisma generate` and did not find your `prisma/schema.prisma`.
If you have a Prisma schema file in a custom path, you will need to run
`prisma generate --schema=./path/to/your/schema.prisma` to generate Prisma Client.
If you do not have a Prisma schema file yet, you can ignore this message.
Environment variables loaded from .env


/root/.npm/_npx/1eeacd173acbda61/node_modules/.prisma/client/index.js:3
    throw new Error(
          ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/root/.npm/_npx/1eeacd173acbda61/node_modules/.prisma/client/index.js:3:11)
    at /root/.npm/_npx/1eeacd173acbda61/node_modules/@umami/migrate-v1-v2/index.js:337:12

Node.js v19.9.0
```

**Comment by seanghay** [comment]
```
Use "@prisma/client/runtime/library",  "@prisma/client/runtime/data-proxy" or  "@prisma/client/runtime/binary"
✓ DATABASE_URL is defined.
✓ Database connection successful.
Preparing v1 tables for migration
✓ Dropped v1 database keys.
PrismaClientKnownRequestError:
Invalid `prisma.$executeRaw()` invocation:


Raw query failed. Code: `2BP01`. Message: `db error: ERROR: cannot drop index website_share_id_key because constraint website_share_id_key on table website requires it
HINT: You can drop constraint website_share_id_key on table website instead.`
    at ba.handleRequestError (/app/node_modules/@umami/migrate-v1-v2/node_modules/@prisma/client/runtime/index.js:263:6415)
    at ba.handleAndLogRequestError (/app/node_modules/@umami/migrate-v1-v2/node_modules/@prisma/client/runtime/index.js:263:5949)
    at ba.request (/app/node_modules/@umami/migrate-v1-v2/node_modules/@prisma/client/runtime/index.js:263:5787)
    at async Proxy._request (/app/node_modules/@umami/migrate-v1-v2/node_modules/@prisma/client/runtime/index.js:266:10745) {
  code: 'P2010',
  clientVersion: '4.9.0',
  meta: {
    code: '2BP01',
    message: 'db error: ERROR: cannot drop index website_share_id_key because constraint website_share_id_key on table website requires it\n' +
      'HINT: You can drop constraint website_share_id_key on table website instead.'
  }
}
✗ 
```

**Comment by franciscao633** [comment]
Did not initialize should be resolved, We updated the docs https://umami.is/docs/migrate-v1-v2. The website_share_id_key working on a fix now. For now you can manually remove the constraint then rerun the migration

**Comment by franciscao633** [comment]
A fix has been pushed to master. Will publish a new version soon.

**Comment by revett** [comment]
@franciscao633 I'm still getting the Prisma error on `v0.13.0`

```
Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
```

```
"@umami/migrate-v1-v2@^0.13.0":
  version "0.13.0"
```

**Comment by franciscao633** [comment]
Can you try running `npx prisma generate`   then `npx @umami/migrate-v1-v2`

If you running the commands in docker you may need to run all 3 in sequence

`yarn add @umami/migrate-v1-v2`
`npx prisma generate`
`npx @umami/migrate-v1-v2`

**Comment by revett** [comment]
@franciscao633 Few issues but I got it working, solution was:

1. `yarn add @umami/migrate-v1-v2`
2. `npx prisma generate --schema=./db/postgresql/schema.prisma`
3. `mkdir prisma`
4. `cp db/postgresql/schema.prisma prisma/schema.prisma`
5. `DATABASE_URL="..." npx @umami/migrate-v1-v2`

**Comment by bergpb** [comment]
I have a similar issue here, I created a docker image to run with Standalone steps and the same error is showed when I run `yarn start` command.
Here the Dockerfile:
```
FROM node:16

ENV DATABASE_URL=postgresql://username:password@db:5432/umami

COPY . /home/node/

WORKDIR /home/node

RUN yarn install && \
    yarn build

CMD ["/bin/bash"]
```

Here the output:
```
root@7dd3d4b59153:/home/node# yarn start
yarn run v1.22.19
$ node index.js
Running v0.15.0
/home/node/node_modules/.prisma/client/index.js:3
    throw new Error(
          ^

Error: @prisma/client did not initialize yet. Please run "prisma generate" and try to import it again.
In case this error is unexpected for you, please report it in https://github.com/prisma/prisma/issues
    at new PrismaClient (/home/node/node_modules/.prisma/client/index.js:3:11)
    at /home/node/index.js:294:12
    at Object.<anonymous> (/home/node/index.js:319:3)
    at Module._compile (node:internal/modules/cjs/loader:1196:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
    at Module.load (node:internal/modules/cjs/loader:1074:32)
    at Function.Module._load (node:internal/modules/cjs/loader:909:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:22:47
error Command failed with exit code 1.
```
